pi/common: script to create .img
skiffos/SkiffOS pull request #148
Opened 2021-05-01 23:16 UTC by luisbc92

This pull request adds a script to ease the creation of .img sd card images for Raspberry Pi.

Usage:
```sh
$ export PI_IMAGE=sdcard.img
$ sudo -E make cmd/pi/common/create-image
```

The image will be created inside of the current workspace. Alternatively PI_IMAGE can be an absolute path.

This implementation uses **losetup** and therefore still requires root.

@paralin this is from TacosAlPastor in Discord.

2021-05-01 23:37 UTC, paralin requested changes
Looks good! Only thing - need to add `create-image` to the `metadata/commands` file for it to appear in the "help" output.

2021-05-01 23:44 UTC, luisbc92 commented
Right! Added the description now.

2021-05-02 00:00 UTC, paralin approved these changes

2021-05-02 00:00 UTC, merged

2021-05-02 00:01 UTC, paralin commented
@luisbc92 I've rebased the commits a bit on staging and then merged to master.